version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    groups:
      production-dependencies-minor:
        dependency-type: "production"
        update-types:
        - "minor"
        - "patch"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    reviewers:
      - "tomodwyer"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
