version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    groups:
      prod-minor:
        dependency-type: "production"
        update-types: ["minor"]
      prod-patch:
        dependency-type: "production"
        update-types: ["patch"]
      dev-minor-patch:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    reviewers:
      - "tomodwyer"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
