repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    - id: pyupgrade
      language_version: python3.9

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.3.2
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    - id: black
      language_version: python3.9

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      language_version: python3.9

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      language_version: python3.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key

  - repo: https://github.com/stratasan/hadolint-pre-commit
    rev: cdefcb0
    hooks:
    - id: hadolint
