# docker configuration for running a development server
version: "3.6"
services:
  job-server:
    build: .
    environment:
      - OPENSAFELY_JOB_SERVER_SECRET_KEY=${OPENSAFELY_JOB_SERVER_SECRET_KEY:-12345}
      # Credentials for acessing the job server
      - QUEUE_USER=${OPENSAFELY_QUEUE_USER:-queue}
      - QUEUE_PASS=${OPENSAFELY_QUEUE_PASS:-queue}
    ports:
      - "8000:8000"
    entrypoint: /app/entrypoint-dev.sh
    command: /app/manage.py runserver 0.0.0.0:8000
