[tool.black]
exclude = '''
(
  /(
      \.direnv
    | \.git
    | \.github
    | \.ipynb_checkpoints
    | \.pytest_cache
    | \.venv
    | assets
    | coverage
    | htmlcov
    | node_modules
    | outputs
    | releases
    | snippets
    | static
    | staticfiles
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
  "jobserver/asgi.py",
  "jobserver/management/commands/count_rows.py",
  "jobserver/management/commands/ensure_admins.py",
  "jobserver/management/commands/release.py",
  "jobserver/migrations/*",
  "jobserver/settings.py",
  "jobserver/wsgi.py",
  "services/sentry.py",
]

[tool.coverage.report]
fail_under = 100
skip_covered = true

[tool.coverage.html]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
skip_glob = [".direnv", "venv", ".venv"]
use_parentheses = true

[tool.pytest.ini_options]
addopts = "--disable-network --tb=native --no-migrations"
DJANGO_SETTINGS_MODULE = "jobserver.settings"
env = [
  "AUTHORIZATION_ORGS=opensafely",
  "GITHUB_TOKEN=empty",
  "SECRET_KEY=12345",
  "SOCIAL_AUTH_GITHUB_KEY=test",
  "SOCIAL_AUTH_GITHUB_SECRET=test",
]
filterwarnings = [
    "error",
    "ignore:'debug_toolbar':django.utils.deprecation.RemovedInDjango41Warning:django",
    "ignore:A private pytest class or function was used.:pytest.PytestDeprecationWarning:pytest_subtests",
    "ignore::pytest.PytestUnraisableExceptionWarning:",
]
