[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.direnv
    | \.venv
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
  "jobserver/asgi.py",
  "jobserver/management/commands/backfill_org_memberships.py",
  "jobserver/management/commands/backfill_project_dot_yamls.py",
  "jobserver/management/commands/create_project_from_workspace.py",
  "jobserver/management/commands/ensure_admins.py",
  "jobserver/management/commands/link_user_to_project.py",
  "jobserver/management/commands/link_workspace_to_project.py",
  "jobserver/management/commands/local_data.py",
  "jobserver/migrations/*",
  "jobserver/settings.py",
  "jobserver/wsgi.py",
  "services/sentry.py",
]

[tool.coverage.report]
fail_under = 100
skip_covered = true

[tool.coverage.html]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
skip_glob = [".direnv", "venv", ".venv"]
use_parentheses = true

[tool.pytest.ini_options]
addopts = "--disable-network"
DJANGO_SETTINGS_MODULE = "jobserver.settings"
env = [
  "GITHUB_TOKEN=dummy_token",
  "SECRET_KEY=12345",
  "SOCIAL_AUTH_GITHUB_KEY=test",
  "SOCIAL_AUTH_GITHUB_SECRET=test",
]
filterwarnings = [
    'ignore:django.conf.urls.url\(\) is deprecated:django.utils.deprecation.RemovedInDjango40Warning:rest_framework|social_django',
    "ignore::django.utils.deprecation.RemovedInDjango41Warning:django",
    "ignore:A private pytest class or function was used.:pytest.PytestDeprecationWarning:pytest_subtests",
]
