[tool.black]
exclude = '''
(
  /(
      \.direnv
    | \.git
    | \.github
    | \.ipynb_checkpoints
    | \.pytest_cache
    | \.venv
    | assets
    | coverage
    | htmlcov
    | node_modules
    | outputs
    | releases
    | snippets
    | static
    | staticfiles
    | venv
    | release-hatch
  )/
)
'''

[tool.coverage.run]
branch = true
dynamic_context = "test_function"
omit = [
  "*/migrations/*",
  "jobserver/asgi.py",
  "jobserver/jobs/*",
  "jobserver/management/commands/count_rows.py",
  "jobserver/management/commands/ensure_admins.py",
  "jobserver/management/commands/ensure_backends.py",
  "jobserver/management/commands/inflate_release_files.py",
  "jobserver/management/commands/release.py",
  "jobserver/settings.py",
  "jobserver/wsgi.py",
  "services/sentry.py",
]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = true

[tool.coverage.html]
show_contexts = true

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
skip_glob = [".direnv", "venv", ".venv"]
use_parentheses = true

[tool.pytest.ini_options]
addopts = "--disable-network --tb=native --no-migrations --ignore=./release-hatch"
DJANGO_SETTINGS_MODULE = "jobserver.settings"
env = [
  "GITHUB_TOKEN=empty",
  "SECRET_KEY=12345",
  "SOCIAL_AUTH_GITHUB_KEY=test",
  "SOCIAL_AUTH_GITHUB_SECRET=test",
]
filterwarnings = [
    "error",
    "ignore::pytest.PytestUnraisableExceptionWarning:",
    "ignore:distutils Version classes are deprecated:DeprecationWarning:pytest_freezegun",
]
markers = [
  "verification: tests that verify fakes",
]
