[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.direnv
    | \.venv
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
  "jobserver/asgi.py",
  "jobserver/management/commands/ensure_admins.py",
  "jobserver/management/commands/local_data.py",
  "jobserver/migrations/*",
  "jobserver/settings.py",
  "jobserver/wsgi.py",
]

[tool.coverage.report]
fail_under = 100
skip_covered = true

[tool.coverage.html]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
lines_after_imports = 2
multi_line_output = 3
skip_glob = [".direnv", "venv", ".venv"]
use_parentheses = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "jobserver.settings"
env = [
  "GITHUB_TOKEN=dummy_token",
  "OPENSAFELY_JOB_SERVER_SECRET_KEY=12345",
]
filterwarnings = [
    'ignore:django.conf.urls.url\(\) is deprecated:django.utils.deprecation.RemovedInDjango40Warning:rest_framework|social_django',
]
